.PHONY: run
run:
	pnpm dev

.PHONY: install
install:
	pnpm install

.PHONY: build
build:
	pnpm build

.PHONY: lint
lint:
	pnpm lint

.PHONY: test
test:
	pnpm test

.PHONY: test-watch
test-watch:
	pnpm test watch
