# Run restores, builds, and runs the API.
.PHONY: run
run:
	dotnet run


.PHONY: watch
watch:
	dotnet watch

# Build restores and builds the API.
.PHONY: build
build:
	dotnet build

.PHONY: test
test:
	dotnet test
