# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Lint Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - .github/workflows/lint-frontend.yml
      - 'Okane.Client/**.ts'
      - 'Okane.Client/**.vue'
      - 'Okane.Client/package.json'
      - 'Okane.Client/pnpm-lock.yaml'

jobs:
  lint-frontend:
    defaults:
      run:
        working-directory: Okane.Client

    name: Run frontend linting
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2
        with:
          install: true
          cache: true

      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: pnpm install

      - run: pnpm run lint

