# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Test Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - .github/workflows/test-frontend.yml
      - 'Okane.Client/**.ts'
      - 'Okane.Client/**.vue'
      - 'Okane.Client/package.json'
      - 'Okane.Client/package-lock.json'

jobs:
  test-frontend:
    defaults:
      run:
        working-directory: Okane.Client

    name: Run frontend tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: Okane.Client/package-lock.json

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      - run: npm run build --if-present

      - run: npm test
